# Copyright (c) 2023 Hiroyuki Okada
# This software is released under the MIT License.
# http://opensource.org/licenses/mit-license.php
services:
  hsr_noetic:
    container_name: hsr_noetic
    image: hsr:noetic-nvidia
    build:
      context: .
      args:
      # ${VARIABLE} are defined in .env
        - USER_NAME=${USER_NAME}
        - GROUP_NAME=${GROUP_NAME}
        - PASSWORD=${PASSWORD}
        - UID=${UID}
        - GID=${GID}
        - ROBOT_NAME=${ROBOT_NAME}
        - WORKSPACE_DIR=${WORKSPACE_DIR}
        - NETWORK_IF=${NETWORK_IF}
#      network: host
    security_opt:
    - seccomp:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities:      
                - gpu
#                - utility # nvidia-smi
#                - compute # CUDA
#                - video   # NVDEC/NVENC/NVCUVID. For instance to use a hardware accelerated ffmpeg. Skip it if you don't need itk

    command: bash -c "bash"
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
      - NO_AT_BRIDGE=1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro      
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/home/${USER_NAME}/.Xauthority
      - ${WORKSPACE_DIR}:${WORKSPACE_DIR}
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    devices:
      - /dev/snd:/dev/snd
      - /dev/dri:/dev/dri
    privileged: true
    ipc: host
    user: "${UID}:${GID}"
    group_add:
      - audio
    tty: true
    stdin_open: true
